Controllers/DiscussionController.cs
using Microsoft.AspNetCore.Mvc;
using GamingForum.Models.DiscussionViewModels;
using GamingForum.BusinessManagers.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace GamingForum.Controllers
{
    [Authorize]
    public class DiscussionController : Controller
    {
        private readonly IDiscussionBusinessManager discussionBusinessManager;
        private readonly IAdminBusinessManager adminBusinessManager;
        public DiscussionController(IDiscussionBusinessManager discussionBusinessManager, IAdminBusinessManager adminBusinessManager)
        {
            this.discussionBusinessManager = discussionBusinessManager;
            this.adminBusinessManager = adminBusinessManager;   
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int? id)
        {
            var actionResult = await discussionBusinessManager.GetDiscussionViewModel(id, User);
            if (actionResult.Result is null)
                return View(actionResult.Value);
            return actionResult.Result;
        }

        public IActionResult Create()
        {
			return View(new CreateViewModel());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var actionResult = await discussionBusinessManager.GetEditViewModel(id, User);
            if (actionResult.Result is null)
                return View(actionResult.Value);
            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateViewModel createViewModel)
        {
            if(createViewModel.Discussion.Content == null)
                return RedirectToAction("Create");
            await discussionBusinessManager.CreateDiscussion(createViewModel, User);
            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            await discussionBusinessManager.DeleteDiscussion(id, User);
            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditViewModel editViewModel)
        {
            var actionResult = await discussionBusinessManager.UpdateDiscussion(editViewModel, User);

            if (actionResult.Result is null)
                return RedirectToAction("Edit", new { editViewModel.Discussion.Id });

            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Comment(DiscussionViewModel discussionViewModel)
        {
            var actionResult = await discussionBusinessManager.CreateComment(discussionViewModel, User);

            if (actionResult.Result is null)
                return RedirectToAction("Index", new { discussionViewModel.Discussion.Id });

            return actionResult.Result;
        }
    }
}

ViewComponents/AdminFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace GamingForum.ViewComponents
{
    public class AdminFooterViewComponent : ViewComponent
    { 
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

ViewComponents/AdminSideNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace GamingForum.ViewComponents
{
    public class AdminSideNavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

ViewComponents/AdminTopNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace GamingForum.ViewComponents
{
    public class AdminTopNavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

Views/Admin/Index.cshtml
@model GamingForum.Models.AdminViewModels.IndexViewModel

<div class="container-fluid">
	<h1 class="mt-4">Dashboard</h1>
	<ol class="breadcrumb mb-4">
		<li class="breadcrumb-item active">Your Discussions</li>
	</ol>
	<div class="row">
		@foreach (var discussion in Model.Discussions)
		{
			<div class="col-xl-2 col-md-6 mb-4">
				<div class="cardborder-0 shadow">
					<img src="~/img/@(discussion.GameName).jpg" class="card-img-bottom"> 
					<div class="card-body" >
						<div class="row" style="margin: 0px auto 10px 0px;">
							<div><h5 class="card-title mb-0">@discussion.Title</h5></div>
						</div>
						<div class="row ml-0">
							<div><i class="fas fa-calendar-alt" style="color: gray"></i></div>
							<p class="text-muted ml-3 mb-0">Created on: @discussion.CreatedOn</p>
						</div>
						<div class="row ml-0" style="bottom: 0;">
							<div><i class="fas fa-comment" style="color: gray"></i></div>
							<p class="text-muted ml-3 mb-0">@discussion.Comments.Count() comments</p>
						</div>
					</div>
					<div class="card-footer">
						<div class="row">
							<div class="col">
								<a asp-controller="Discussion" asp-action="Index" asp-route-id="@discussion.Id" class ="btn btn-primary">
									<i class="fa fa-eye"></i>
								</a>
							</div>
							<div class="col">
								<a asp-controller="Discussion" asp-action="Edit" asp-route-id="@discussion.Id" class ="btn btn-secondary float-right">
									<i class="fa fa-pencil"></i>
								</a>
							</div>
							<div class="col">
								<a asp-controller="Discussion" asp-action="Delete" asp-route-id="@discussion.Id" class ="btn btn-danger float-right">
									<i class="fa fa-trash"></i>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>

Views/Admin/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="~/css/styles2.css" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        @await Component.InvokeAsync("AdminTopNav")

        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                @await Component.InvokeAsync("AdminSideNav")
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @RenderBody()
                </main>
                @await Component.InvokeAsync("AdminFooter")
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="~/js/scripts2.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="~/assets/demo/chart-area-demo.js"></script>
        <script src="~/assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="~/js/datatables-simple-demo.js"></script>
    </body>
</html>