Models/HomeViewModels/AuthorViewModel.cs
using GamingForum.Data.Models;
using PagedList.Core;

namespace GamingForum.Models.HomeViewModels
{
    public class AuthorViewModel
    {
        public ApplicationUser Author { get; set; }
        public IPagedList<Discussion> Discussions { get; set; }
        public string SearchString { get; set; }
        public string GameName { get; set; }
        public int PageNumber { get; set; }
    }
}

Controllers/DiscussionController.cs
using Microsoft.AspNetCore.Mvc;
using GamingForum.Models.DiscussionViewModels;
using GamingForum.BusinessManagers.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace GamingForum.Controllers
{
    [Authorize]
    public class DiscussionController : Controller
    {
        private readonly IDiscussionBusinessManager discussionBusinessManager;
        private readonly IAdminBusinessManager adminBusinessManager;
        public DiscussionController(IDiscussionBusinessManager discussionBusinessManager, IAdminBusinessManager adminBusinessManager)
        {
            this.discussionBusinessManager = discussionBusinessManager;
            this.adminBusinessManager = adminBusinessManager;   
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int? id)
        {
            var actionResult = await discussionBusinessManager.GetDiscussionViewModel(id, User);
            if (actionResult.Result is null)
                return View(actionResult.Value);
            return actionResult.Result;
        }

        public IActionResult Create()
        {
			return View(new CreateViewModel());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var actionResult = await discussionBusinessManager.GetEditViewModel(id, User);
            if (actionResult.Result is null)
                return View(actionResult.Value);
            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateViewModel createViewModel)
        {
            if(createViewModel.Discussion.Content == null)
                return RedirectToAction("Create");
            await discussionBusinessManager.CreateDiscussion(createViewModel, User);
            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            await discussionBusinessManager.DeleteDiscussion(id, User);
            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditViewModel editViewModel)
        {
            var actionResult = await discussionBusinessManager.UpdateDiscussion(editViewModel, User);

            if (actionResult.Result is null)
                return RedirectToAction("Edit", new { editViewModel.Discussion.Id });

            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Comment(DiscussionViewModel discussionViewModel)
        {
            var actionResult = await discussionBusinessManager.CreateComment(discussionViewModel, User);

            if (actionResult.Result is null)
                return RedirectToAction("Index", new { discussionViewModel.Discussion.Id });

            return actionResult.Result;
        }
    }
}

Controllers/HomeController.cs
using GamingForum.BusinessManagers.Interfaces;
using GamingForum.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GamingForum.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDiscussionBusinessManager discussionBusinessManager;
        private readonly IHomeBusinessManager homeBusinessManager;
        public HomeController(IDiscussionBusinessManager discussionBusinessManager, IHomeBusinessManager homeBusinessManager)
        {
            this.discussionBusinessManager = discussionBusinessManager;
            this.homeBusinessManager = homeBusinessManager;
        }

        public IActionResult Index(string searchString, string gameName, int? page)
        {
            return View(discussionBusinessManager.GetIndexViewModel(searchString, gameName, page));
        }

        public IActionResult Author(string authorId, string searchString,string gameName, int? page)
        {
            var actionResult = homeBusinessManager.GetAuthorViewModel(authorId, searchString, gameName, page);
            if (actionResult is null)
                return View(actionResult.Value);
            if (actionResult.Result is null)
                return View(actionResult.Value);
            return actionResult.Result;
        }
    }
}

ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace GamingForum.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace GamingForum.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

ViewComponents/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace GamingForum.ViewComponents
{
    public class NavigationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

Views/Home/Author.cshtml
@model GamingForum.Models.HomeViewModels.AuthorViewModel
@using PagedList.Core.Mvc
@{
	Layout = "_HomeLayout";
	ViewData["HeaderImage"] = $"../../img/authorPage.jpg";
	ViewData["HeaderTitle"] = $"{Model.Author.FirstName} {Model.Author.LastName}";
	ViewData["IsAuthor"]= true;
}

<article>
	<div class="containter">
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
				@Html.Raw(Model.Author.FirstName)'s discussions
			</div>
		</div>
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
				<form asp-controller="Home" asp-action="Author" class="d-none d-md-inline-block form-check-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
					<div class="input-group mb-3">
						<input name="AuthorId" hidden readonly value="@Model.Author.Id"/>
						<input asp-for="SearchString" type="text" class="form-control" placeholder="..."/>
						<div class="input-group-append">
							<button class="btn btn-outline-secondary" style="padding: 0 10px 0 10px">Search</button>
						</div>
					</div>
				</form>
				<div class="row align-content-center">
					@foreach(var discussion in Model.Discussions)
					{
						<div class="col-lg-4 col-md-3 mb-4">
							<div class="card border-0 shadow">
								@*<img src="~/img/@(discussion.GameName).jpg" class="card-img-top">*@
								<a asp-controller="Discussion" asp-action="Index" asp-route-id="@discussion.Id"><img src="~/img/@(discussion.GameName).jpg" class="card-img-bottom"></a>
								@*<div class="card-body">
									<div class="row text-center" style="margin: 0px auto 10px 0px;">
										<h5 class="card-title text-center w-100"><a asp-controller="Discussion" asp-action="Index" asp-route-id="@discussion.Id">@discussion.Title</a></h5>
									</div>
								</div>*@
								<div class="card-body">
									<div class="row" style="margin: 0px auto 10px 0px;">
										<div><h5 class="card-title text-center w-100"><a asp-controller="Discussion" asp-action="Index" asp-route-id="@discussion.Id">@discussion.Title</a></h5></div>
									</div>
									<div class="row ml-0">
										<div></div>
										<p class="text-muted ml-3 mb-0" style="font-size: 15px"><i class="fas fa-calendar-alt" style="color: gray"></i> Created on: @discussion.CreatedOn</p>
									</div>
									<div class="row ml-0" style="bottom: 0;">
										<div></div>
										<p class="text-muted ml-3 mb-0" style="font-size: 15px"><i class="fas fa-comment" style="color: gray"></i> @discussion.Comments.Count() comments</p>
									</div>
								</div>
							</div>
						</div>
					}
				</div>
				@*<div list="@Model.Discussions" count="20">*@
					<pager class="pager-container" list="@Model.Discussions" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusPrevAndNext" asp-action="Author" asp-controller="Home" asp-route-query="@Model.SearchString" />
				@*</div>*@
			</div>
		</div>
	</div>
</article>

Views/Home/Index.cshtml
@model GamingForum.Models.HomeViewModels.IndexViewModel
@using PagedList.Core.Mvc

<div class="container">
	<form asp-controller="Home" asp-action="Index" class="d-none d-md-inline-block form-check-inline m-lg-auto mr-0 mr-md-3 my-md-0">
		<div class="input-group mb-3">
			<input asp-for="SearchString" type="text" class="form-control" placeholder="Search" />
			@*<input asp-for="GameName" type="text" class="form-control" placeholder="Game" />*@
			<select asp-for="GameName" class="form-control" required>
				<option value=" ">Game Name...</option>
				<option value="Runescape3">Runescape3</option>
				<option value="Old School Runescape">Old School Runescape</option>
				<option value="World Of Warcraft">World Of Warcraft</option>
				<option value="Maplestory">MapleStory</option>
			</select>
			<div class=input-group-append>
				<button class="btn btn-outline-secondary " style="padding: 0 10px 0 10px;">Search</button>
			</div>
		</div>
	</form>
	<div class="row align-content-center">
		@foreach(var discussion in Model.Discussions)
		{
			<div class="col-lg-3 col-md-3 mb-4">
				<div class="cardborder-0 shadow">
					@*<img src="~/img/@(discussion.GameName).jpg" class="card-img-bottom">*@
					<a asp-controller="Discussion" asp-action="Index" asp-route-id="@discussion.Id"><img src="~/img/@(discussion.GameName).jpg" class="card-img-bottom"></a>
					@*<div class="card-body">
						<div class="row text-center" style="margin: 0px auto 10px 0px;">
							<h5 class="card-title text-center w-100"><a asp-controller="Discussion" asp-action="Index" asp-route-id="@discussion.Id">@discussion.Title</a></h5>
						</div>
					</div>*@
					<div class="card-body">
						<div class="row" style="margin: 0px auto 10px 0px;">
							<div><h5 class="card-title text-center w-100"><a asp-controller="Discussion" asp-action="Index" asp-route-id="@discussion.Id">@discussion.Title</a></h5></div>
						</div>
						<div class="row ml-0">
							<div></div>
							<p class="text-muted ml-3 mb-0"><i class="fas fa-calendar-alt" style="color: gray"></i> Created on: @discussion.CreatedOn</p>
						</div>
						<div class="row ml-0" style="bottom: 0;">
							<div></div>
							<p class="text-muted ml-3 mb-0"><i class="fas fa-comment" style="color: gray"></i> @discussion.Comments.Count() comments</p>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
	@*<div list="@Model.Discussions" count="9">*@
		<pager class="pager-container" list="@Model.Discussions" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusPrevAndNext" asp-action="Index" asp-controller="Home" asp-route-query="@Model.SearchString" />
	@*</div>*@
</div>

Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Gaming Forum - By Shahar Cohen</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="~/css/styles.css" rel="stylesheet" />
    </head>
<body>
        @await Component.InvokeAsync("Navigation")
        
        @await Component.InvokeAsync("Header")

        <div class="content">
            @RenderBody()
        </div>

        @RenderBody();

        @await Component.InvokeAsync("Footer")
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="~/js/scripts.js"></script>
    </body>
</html>