Controllers/AdminController.cs
using GamingForum.BusinessManagers.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GamingForum.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IAdminBusinessManager adminBusinessManager;
        public AdminController(IAdminBusinessManager adminBusinessManager)
        {
            this.adminBusinessManager = adminBusinessManager;
        }
        public async Task<IActionResult> Index()
        {
            return View(await adminBusinessManager.GetAdminDashboard(User));
        }

    }
}

Controllers/DiscussionController.cs
using Microsoft.AspNetCore.Mvc;
using GamingForum.Models.DiscussionViewModels;
using GamingForum.BusinessManagers.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace GamingForum.Controllers
{
    [Authorize]
    public class DiscussionController : Controller
    {
        private readonly IDiscussionBusinessManager discussionBusinessManager;
        private readonly IAdminBusinessManager adminBusinessManager;
        public DiscussionController(IDiscussionBusinessManager discussionBusinessManager, IAdminBusinessManager adminBusinessManager)
        {
            this.discussionBusinessManager = discussionBusinessManager;
            this.adminBusinessManager = adminBusinessManager;   
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int? id)
        {
            var actionResult = await discussionBusinessManager.GetDiscussionViewModel(id, User);
            if (actionResult.Result is null)
                return View(actionResult.Value);
            return actionResult.Result;
        }

        public IActionResult Create()
        {
			return View(new CreateViewModel());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var actionResult = await discussionBusinessManager.GetEditViewModel(id, User);
            if (actionResult.Result is null)
                return View(actionResult.Value);
            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateViewModel createViewModel)
        {
            if(createViewModel.Discussion.Content == null)
                return RedirectToAction("Create");
            await discussionBusinessManager.CreateDiscussion(createViewModel, User);
            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            await discussionBusinessManager.DeleteDiscussion(id, User);
            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditViewModel editViewModel)
        {
            var actionResult = await discussionBusinessManager.UpdateDiscussion(editViewModel, User);

            if (actionResult.Result is null)
                return RedirectToAction("Edit", new { editViewModel.Discussion.Id });

            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Comment(DiscussionViewModel discussionViewModel)
        {
            var actionResult = await discussionBusinessManager.CreateComment(discussionViewModel, User);

            if (actionResult.Result is null)
                return RedirectToAction("Index", new { discussionViewModel.Discussion.Id });

            return actionResult.Result;
        }
    }
}

Views/Shared/Components/AdminSideNav/Default.cshtml
@using Microsoft.AspNetCore.Identity
@using GamingForum.Data.Models

@inject UserManager<ApplicationUser> UserManager

<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <a class="nav-link" asp-controller="Admin" asp-action="index">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Dashboard
            </a>
            <a class="nav-link" asp-controller="Discussion" asp-action="Create">
                <div class="sb-nav-link-icon"><i class="fas fa-pen"></i></div>
                Create Discussion
            </a>
        </div>
    </div>
    <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        @((await UserManager.GetUserAsync(User)).FirstName) @((await UserManager.GetUserAsync(User)).LastName )
    </div>
</nav>